### ISSUE TITLE
Feature 1: Display Active Movies

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/movieratingapp-core-kannan#1]
The proper format is done as below to display the moviedetails

**Comment by csys-fresher-batch-2021** [comment]
##### Movies 

- [ ] Create a table movies
- [ ] Create a dao for movies 
- [ ] Create a model
- [ ] Create a test class
- [ ] Create a Service class


| id  | name   |  release_date  | active  |  end_date  |
|---|---|---|---|---|
|  1 | Master  | 2021-01-01  | true  | 2021-05-31  |
|  2 | Karnan  | 2021-03-01  | true  | 2021-06-31  |

**Comment by KANNAN84-hash** [comment]
I have completed the display feature to display the movie details for the users .

**Comment by KANNAN84-hash** [comment]
**Display  feature**

![image](https://user-images.githubusercontent.com/82588986/121457750-cd989000-c9c5-11eb-88e6-441f57615080.png)
