### ISSUE TITLE
Feature 2: Admin Login

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/movieratingapp-core-kannan#2]

**Comment by KANNAN84-hash** [comment]
**SUCCESS CASE**

 
![image](https://user-images.githubusercontent.com/82588986/121374862-e1101080-c95d-11eb-9eb5-135052f1b88d.png)

**Comment by KANNAN84-hash** [comment]
**WHEN USER TRIES TO LOG IN ADMIN PAGE**



![image](https://user-images.githubusercontent.com/82588986/121375145-203e6180-c95e-11eb-96ce-a998839d97fd.png)

**Comment by KANNAN84-hash** [comment]
#### WHEN USER ENTERS INVALID DETAILS i.e. WRONG EMAIL OR PASSWORD


![image](https://user-images.githubusercontent.com/82588986/121375770-9b077c80-c95e-11eb-9b4b-7164574b1157.png)

**Comment by KANNAN84-hash** [comment]
**WHEN ADMIN ENTERS WRONG PASSWORD FORMAT**


![image](https://user-images.githubusercontent.com/82588986/121376679-57614280-c95f-11eb-972e-cabcd2ba357a.png)

**Comment by KANNAN84-hash** [comment]
**WHEN ADMIN ENTERS WRONG EMAIL FORMAT **


![image](https://user-images.githubusercontent.com/82588986/121376888-88417780-c95f-11eb-9600-ba967fae8da5.png)
