### ISSUE TITLE
Feature 3: Add Movie

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/movieratingapp-core-kannan#3]
Added movie detail in movies table using sql folder

**Comment by KANNAN84-hash** [comment]
**ADDED MOVIE DETAIL IN SQL FOLDER**

![image](https://user-images.githubusercontent.com/82588986/121520359-74a21980-ca10-11eb-8b07-1ca5e3e8535c.png)

**Comment by KANNAN84-hash** [comment]
**SUCCESS CASE:**
![image](https://user-images.githubusercontent.com/82588986/122943215-736bd780-d394-11eb-800c-d3cf7c32f911.png)
![image](https://user-images.githubusercontent.com/82588986/122943272-7f579980-d394-11eb-84dd-0857f5cbc92a.png)

**Comment by KANNAN84-hash** [comment]
**FAILURE CASE :1 WHEN INVALID MOVIE NAME IS GIVEN**

![image](https://user-images.githubusercontent.com/82588986/122943703-deb5a980-d394-11eb-98f0-b86272172349.png)

**Comment by KANNAN84-hash** [comment]
**FAILURE CASE 2: WHEN EARLIER REGISTERED MOVIE IS REGISTERED AGAIN**

![image](https://user-images.githubusercontent.com/82588986/122943834-fb51e180-d394-11eb-85fd-10b9e7613aad.png)

**Comment by KANNAN84-hash** [comment]
**WHEN ADMIN FORGET TO ENTER THE DATE:**

![image](https://user-images.githubusercontent.com/82588986/122944208-3eac5000-d395-11eb-8a29-c40033ed537d.png)
