### ISSUE TITLE
Feature 5: Add Movie Ratings by User

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/movieratingapp-core-kannan#5]

**Comment by KANNAN84-hash** [comment]
### Success case 1
**Before rating by a particular user in movie_rating table**
![image](https://user-images.githubusercontent.com/82588986/121790891-daa1c300-cc01-11eb-8145-be4cc42ad910.png)

**Comment by KANNAN84-hash** [comment]
### Success case 1
**When user of user Id 6 rates the movie of movie id  4 with the rating of 6**
![image](https://user-images.githubusercontent.com/82588986/121791046-3ae53480-cc03-11eb-9a15-7a83bd008d2d.png)
![image](https://user-images.githubusercontent.com/82588986/121791059-518b8b80-cc03-11eb-8fc0-70a19ae98ef8.png)

![image](https://user-images.githubusercontent.com/82588986/121791226-36ba1680-cc05-11eb-9bd4-3487d80d3846.png)

**Comment by KANNAN84-hash** [comment]
**Unsuccessful case 1**
### When the user tries to register for the same movie another time
![image](https://user-images.githubusercontent.com/82588986/121791093-c8288900-cc03-11eb-8305-e4cfe60d7bf9.png)

**Comment by KANNAN84-hash** [comment]
**unsuccessful case 2**
### when admin tries to rate the movie
![image](https://user-images.githubusercontent.com/82588986/121791188-d3c87f80-cc04-11eb-925c-b27a69e17e5e.png)

**Comment by KANNAN84-hash** [comment]
**Unsuccess case**
### Unregistered movie id
![image](https://user-images.githubusercontent.com/82588986/121791263-a9c38d00-cc05-11eb-9ae5-e35b58a4de65.png)
