### ISSUE TITLE
Feature 6: Display Movie with Movie Ratings

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/movieratingapp-core-kannan#6]

**Comment by KANNAN84-hash** [comment]
**Displaying Movie Name Along with Users Rating:** 

![image](https://user-images.githubusercontent.com/82588986/122939422-3baf6080-d391-11eb-9a3b-69455d3b00d8.png)

Next in console

![image](https://user-images.githubusercontent.com/82588986/122939918-a791c900-d391-11eb-8c69-9ff314f905d0.png)
